# Generated by Django 6.1.1 on 2026-09-03 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('rango_edad_ref', models.CharField(blank=True, help_text='Ej: 6-7 años. Solo referencial, la categoría real la define el campeonato.', max_length=40, verbose_name='Rango de edad de referencia')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('ciudad', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubes',
            },
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('region', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name': 'Liga',
                'verbose_name_plural': 'Ligas',
            },
        ),
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('temporada', models.CharField(help_text='Ej: 2025-2026', max_length=20)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campeonatos', to='jugadores.categoria')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campeonatos', to='jugadores.liga')),
            ],
            options={
                'verbose_name': 'Campeonato',
                'verbose_name_plural': 'Campeonatos',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escuadra', models.CharField(blank=True, help_text='Letra o identificador de la escuadra dentro del club, ej: A, D, D1', max_length=10)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='jugadores.campeonato')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='jugadores.club')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateField()),
                ('posicion_campo', models.CharField(blank=True, choices=[('lanzador', 'Lanzador'), ('receptor', 'Receptor'), ('1b', 'Primera base'), ('2b', 'Segunda base'), ('3b', 'Tercera base'), ('ss', 'Campocorto'), ('lf', 'Jardinero izquierdo'), ('cf', 'Jardinero central'), ('rf', 'Jardinero derecho')], max_length=10)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='jugadores.equipo')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PerfilAdministrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin_club', 'Administrador de club'), ('admin_liga', 'Administrador de liga')], default='admin_club', max_length=20)),
                ('club', models.ForeignKey(blank=True, help_text='Requerido si el rol es Administrador de club', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administradores', to='jugadores.club')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de administrador',
                'verbose_name_plural': 'Perfiles de administradores',
            },
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('eliminatoria', 'Eliminatoria'), ('round_robin', 'Round Robin'), ('final', 'Final')], default='round_robin', max_length=20)),
                ('juegos', models.PositiveIntegerField(default=0)),
                ('ganados', models.PositiveIntegerField(default=0)),
                ('perdidos', models.PositiveIntegerField(default=0)),
                ('empatados', models.PositiveIntegerField(default=0)),
                ('carreras_favor', models.PositiveIntegerField(default=0)),
                ('carreras_contra', models.PositiveIntegerField(default=0)),
                ('puntos', models.PositiveIntegerField(default=0)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posiciones', to='jugadores.campeonato')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posiciones', to='jugadores.equipo')),
            ],
            options={
                'verbose_name': 'Posición',
                'verbose_name_plural': 'Tabla de posiciones',
            },
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('relacion', models.CharField(choices=[('padre', 'Padre'), ('madre', 'Madre'), ('tutor', 'Tutor legal'), ('otro', 'Otro representante')], max_length=10)),
                ('contacto', models.CharField(blank=True, max_length=150)),
                ('consentimiento', models.BooleanField(default=False, help_text='Debe estar marcado antes de publicar cualquier video o foto del jugador.', verbose_name='Consentimiento otorgado')),
                ('fecha_consentimiento', models.DateField(blank=True, null=True)),
                ('jugador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='representante', to='jugadores.jugador')),
            ],
            options={
                'verbose_name': 'Representante',
                'verbose_name_plural': 'Representantes',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_toma', models.CharField(choices=[('bateo', 'Bateo'), ('lanzamiento', 'Lanzamiento'), ('fildeo_infield', 'Fildeo — cuadro'), ('fildeo_outfield', 'Fildeo — jardines'), ('catcher', 'Receptor'), ('corrido_bases', 'Corrido de bases')], max_length=20)),
                ('fecha', models.DateField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='videos/%Y/%m/')),
                ('visibilidad', models.CharField(choices=[('equipo', 'Solo el equipo'), ('representante', 'Solo el representante'), ('publico', 'Público')], default='equipo', max_length=20)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='jugadores.jugador')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['-fecha'],
            },
        ),
    ]
