# Generated by Django 6.1.1 on 2026-09-04 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticaJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('rival', models.CharField(blank=True, max_length=150)),
                ('posicion_jugada', models.CharField(blank=True, choices=[('lanzador', 'Lanzador'), ('receptor', 'Receptor'), ('1b', 'Primera base'), ('2b', 'Segunda base'), ('3b', 'Tercera base'), ('ss', 'Campocorto'), ('lf', 'Jardinero izquierdo'), ('cf', 'Jardinero central'), ('rf', 'Jardinero derecho')], max_length=10)),
                ('turnos', models.PositiveIntegerField(default=0, verbose_name='Turnos al bate')),
                ('hits', models.PositiveIntegerField(default=0)),
                ('carreras_anotadas', models.PositiveIntegerField(default=0)),
                ('impulsadas', models.PositiveIntegerField(default=0)),
                ('bases_robadas', models.PositiveIntegerField(default=0)),
                ('ponches', models.PositiveIntegerField(default=0)),
                ('base_por_bolas', models.PositiveIntegerField(default=0)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas_juego', to='jugadores.jugador')),
            ],
            options={
                'verbose_name': 'Estadística de juego',
                'verbose_name_plural': 'Estadísticas de juego',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros', to='jugadores.jugador')),
            ],
            options={
                'verbose_name': 'Logro',
                'verbose_name_plural': 'Logros',
                'ordering': ['-temporada'],
            },
        ),
    ]
