# Generated by Django 6.1.1 on 2026-09-04 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0002_estadisticajuego_logro'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadisticajuego',
            name='asistencias',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadisticajuego',
            name='base_por_bolas_permitidas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadisticajuego',
            name='carreras_permitidas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadisticajuego',
            name='dobles',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadisticajuego',
            name='equipo',
            field=models.ForeignKey(blank=True, help_text="Equipo/temporada con el que jugó este partido. Permite separar 'esta temporada' de 'de por vida'.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas_juego', to='jugadores.equipo'),
        ),
        migrations.AddField(
            model_name='estadisticajuego',
            name='errores',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadisticajuego',
            name='hits_permitidos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadisticajuego',
            name='jonrones',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadisticajuego',
            name='outs_lanzados',
            field=models.PositiveIntegerField(default=0, help_text='3 outs = 1 entrada. Ej: 4 entradas y 1 out = 13.', verbose_name='Outs lanzados'),
        ),
        migrations.AddField(
            model_name='estadisticajuego',
            name='ponches_pitcheo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadisticajuego',
            name='putouts',
            field=models.PositiveIntegerField(default=0, verbose_name='Outs realizados (PO)'),
        ),
        migrations.AddField(
            model_name='estadisticajuego',
            name='triples',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='juego',
            field=models.ForeignKey(blank=True, help_text='Si esta toma ocurrió en un juego específico, vincúlala aquí para que aparezca en su carta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='jugadores.estadisticajuego'),
        ),
    ]
