# Generated by Django 6.1.1 on 2026-09-04 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0003_estadisticajuego_asistencias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadisticajuego',
            name='estadio',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='estadisticajuego',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
