# Generated by Django 6.1.1 on 2026-09-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0004_estadisticajuego_estadio_estadisticajuego_hora'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['orden'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Define el orden en que aparece la categoría en las listas (menor primero).'),
        ),
    ]
