# Generated by Django 6.1.1 on 2026-09-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0005_alter_categoria_options_categoria_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiladministrador',
            name='rol',
            field=models.CharField(choices=[('admin_club', 'Administrador de club'), ('admin_liga', 'Administrador de liga'), ('camarografo', 'Camarógrafo / Encargado de video')], default='admin_club', max_length=20),
        ),
    ]
