# Generated by Django 6.1.1 on 2026-09-06 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0006_alter_perfiladministrador_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiladministrador',
            name='club',
            field=models.ForeignKey(blank=True, help_text='Requerido si el rol es Administrador de club. Para Camarógrafo, déjalo vacío si debe cubrir TODOS los equipos de la liga, o elige un club si solo debe cubrir ese club.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administradores', to='jugadores.club'),
        ),
    ]
