# Generated by Django 6.1.1 on 2026-09-11 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0007_alter_perfiladministrador_club'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadisticajuego',
            options={'ordering': ['-partido__fecha'], 'verbose_name': 'Estadística de juego', 'verbose_name_plural': 'Estadísticas de juego'},
        ),
        migrations.RemoveField(
            model_name='estadisticajuego',
            name='estadio',
        ),
        migrations.RemoveField(
            model_name='estadisticajuego',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='estadisticajuego',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='estadisticajuego',
            name='rival',
        ),
        migrations.AlterField(
            model_name='estadisticajuego',
            name='equipo',
            field=models.ForeignKey(blank=True, help_text='Equipo con el que jugó este partido (normalmente el equipo actual del jugador).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas_juego', to='jugadores.equipo'),
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('estadio', models.CharField(blank=True, max_length=150)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='jugadores.campeonato')),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='jugadores.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='jugadores.equipo')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='estadisticajuego',
            name='partido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='jugadores.partido'),
        ),
    ]
